// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Clears__OperatorsSelectComponentController from "@components/clears/operators_select_component_controller"
application.register("clears--operators-select-component", Clears__OperatorsSelectComponentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
