require:
  - rubocop-rails
  - rubocop-rspec
  - 'test_prof/rubocop'
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/*'
