require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
RSpec:
  Severity: info
RSpec/MultipleExpectations:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/**/*"
    - "db/**/*"
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Rspec/VerifiedDoubles:
  Enabled: false
Rspec/ExampleLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "app/components/**/*"
