require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
inherit_gem:
  test-prof: config/rubocop-rspec.yml
AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
RSpec:
  Severity: info
RSpec/MultipleExpectations:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - "spec/**/*"
    - "db/**/*"
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: "snake_case"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "lib/tasks/**/*"
RSpec/NestedGroups:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
