databases:
  - name: akclear
    databaseName: akclear
    user: akclear
    plan: free

services:
  - type: web
    plan: free
    name: akclear
    runtime: docker
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: akclear
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
