databases:
  - name: akclear
    databaseName: akclear
    user: akclear
    plan: free

services:
  - type: web
    plan: free
    name: akclear
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: akclear
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: NODE_VERSION
        value: 16.16.0
