databases:
  - name: akclear
    databaseName: akclear
    user: akclear
    plan: free

services:
  - type: worker
    name: goodjob-worker
    runtime: docker
    dockerCommand: bundle exec good_job start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: akclear
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: web
    plan: free
    name: akclear
    runtime: docker
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: akclear
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
